apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ name }}
spec:
  refreshInterval: {{ refreshinterval }}s
  secretStoreRef:
    name: {{ name }}
    kind: SecretStore
  target:
    name: {{ name }}
  data: 
  {%- if dcpSecretStoreKeyRefs is defined and dcpSecretStoreKeyRefs|length > 0 %}
  {%- for item in dcpSecretStoreKeyRefs %}
  - secretKey: {{ item.secretkey }}
    remoteRef:
      key: {{ item.remotekey }}
      property: {{ item.remoteproperty }}
  {%- endfor %}
  {%- endif %}